// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbLn6QpvFuBb1IGWlwOu64_esyV4ZDjxE',
    appId: '1:186205367841:web:9569d139b4f35028de7d60',
    messagingSenderId: '186205367841',
    projectId: 'ossapp-8a1e2',
    authDomain: 'ossapp-8a1e2.firebaseapp.com',
    storageBucket: 'ossapp-8a1e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU2JbUrVNQZX0t-Rj_GgfS0YI65-OO5gU',
    appId: '1:186205367841:android:6a5a9ba325b37a8cde7d60',
    messagingSenderId: '186205367841',
    projectId: 'ossapp-8a1e2',
    storageBucket: 'ossapp-8a1e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtlCniPO4THVZFeg4Xrofyw8RCZ4iNh1E',
    appId: '1:186205367841:ios:e229184a2f9163ffde7d60',
    messagingSenderId: '186205367841',
    projectId: 'ossapp-8a1e2',
    storageBucket: 'ossapp-8a1e2.appspot.com',
    iosClientId: '186205367841-3cd7gjms6ahu11e0bag8f7u937876057.apps.googleusercontent.com',
    iosBundleId: 'com.example.dateapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtlCniPO4THVZFeg4Xrofyw8RCZ4iNh1E',
    appId: '1:186205367841:ios:e229184a2f9163ffde7d60',
    messagingSenderId: '186205367841',
    projectId: 'ossapp-8a1e2',
    storageBucket: 'ossapp-8a1e2.appspot.com',
    iosClientId: '186205367841-3cd7gjms6ahu11e0bag8f7u937876057.apps.googleusercontent.com',
    iosBundleId: 'com.example.dateapp',
  );
}
